class Key:
    row = "row"
    key = "key"
    on = "on"
    last = "last"
    isValid = "isValid"
    value = "value"
    prices = "prices"
    error = "error"
    wait = "_!_ЖДИ_!_"
    sheetName = "sheetName"
    url = "url"
    goods_count = "goods_count"


class SheetNames:
    НеОпределён = "Не Определён"
    # Аналитика = "Аналитика"
    # Парсинг = "Парсинг"
    # Парсинг_Экспресс = "Парсинг Экспресс"
    # Настройки = "Настройки"
    Предметы = "Предметы"
    Карточки = "Карточки"
    Задачи = "Задачи"
    Продавцы = "Продавцы"
